CREATE TABLE IF NOT EXISTS health_runs (
    run_id VARCHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(16) NOT NULL,
    checked_at DATETIME(3) NOT NULL,
    summary JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS health_items (
    run_id VARCHAR(36) NOT NULL,
    code VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    summary VARCHAR(255) NOT NULL DEFAULT '',
    value DOUBLE NULL,
    unit VARCHAR(32) NULL,
    PRIMARY KEY (run_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS backup_records (
    backup_id VARCHAR(36) NOT NULL PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    restore_status VARCHAR(32) NULL,
    restore_checked_at DATETIME(3) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
